name: Test

on:
   pull_request:
      types:
         - opened
         - synchronize
         - reopened

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
         -  uses: actions/checkout@master

         -  name: Test
            run: |
               npm ci
               npm test
